[build]
  base = "telo-mini-fronted"
  publish = "build"
  command = "npm run build"
  ignore_submodules = true

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
