[phases.setup]
nixPkgs = ["nodejs", "php", "php81Extensions.pdo_mysql", "php81Extensions.pdo_pgsql"]
cmds = ["npm install -g serve"]

[phases.build]
cmds = [
  "echo 'Skipping frontend build for now'",
  "cd telo-mini-backend && composer install --no-dev"
]

[start]
cmd = "cd telo-mini-backend && php artisan serve --host=0.0.0.0 --port=$PORT"
